# 参考：https://github.com/Lruihao/hugo-blog/blob/main/config.toml

title = "Yangliuly1"
baseURL = "https://yangliuly1.github.io/"
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# gitRepo
enableGitInfo = true

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

# -------------------------------------------------------------------------------------
# Menu Settings
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = "所有文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
    # 向菜单项添加用户定义的内容
    [menu.main.params]
      # 添加 CSS 类到菜单项
      class = ""
      # 是否为草稿菜单，类似草稿页面
      draft = false
      # 添加 fontawesome 图标到菜单项
      icon = "fa-solid fa-archive"
      # 设置菜单项类型，可选值：["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  # [[menu.main]]  # data/friends.yml friends/index.md friends/opml.xml  #TODO
  #   identifier = "friends"
  #   pre = ""
  #   post = ""
  #   name = "友链"
  #   url = "/friends/"
  #   title = "友情链接"
  #   weight = 4
  [[menu.main]]  
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-user-tie"
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/yangliuly1"
    title = "个人 GitHub"
    weight = ""
    [menu.main.params]
      class = "text-center"
      type = "mobile"

# -------------------------------------------------------------------------------------
# Theme Core Configuration Settings
# -------------------------------------------------------------------------------------

[params]
  # FixIt CHANGED | 0.2.0 FixIt 主题版本
  version = "0.2.X" # 例如："0.2.X", "0.2.15", "v0.2.15" 等
  # 网站描述
  description = "个人博客：探索、分享、记录自己在工作生活学习到一些东西。人知道得越多，就就会发现无知的越多。有更广袤世界可以探索，真是莫大的快乐啊！"
  # 网站关键词
  keywords = ["Yangliuly1", "Hugo Blog"]
  # 网站默认主题样式 ["light", "dark", "auto"]
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/Yangliuly1/hugo-blog"
  #  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  #  日期格式
  dateFormat = "2006-01-02"
  # 网站图片，用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
  #  开启 PWA 支持
  enablePWA = true
  #  是否自动显示外链图标
  externalIcon = false
  #  默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记
  # 您可以将其关闭，但如果您不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法
  disableThemeInject = false

  # FixIt NEW | 0.2.0 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
    title = "坚持不懈"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"
    #  Android 浏览器主题色
    [params.app.themeColor]
      light = "#ffffff"
      dark = "#252627"

  # FixIt NEW | 0.2.0 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # FixIt NEW | 0.2.1 最大结果数目
    maxResultLength = 10
    # FixIt NEW | 0.2.3 结果内容片段长度
    snippetLength = 50
    # FixIt NEW | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # FixIt NEW | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = "index"
      appID = "XJWBTN7H9R"
      searchKey = "e3b2e259867b44c8dc21804d060c22cb"

  # 页面头部导航栏配置
  [params.header]
    #  桌面端导航栏模式 ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    #  移动端导航栏模式 ["sticky", "normal", "auto"]
    mobileMode = "auto"
    #  页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/imgs/favicon/favicon.ico"
      # 标题名称
      name = "坚持不懈"
      # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
      pre = ""
      # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
      post = ""
      #  是否为标题显示打字机动画
      typeit = false
    #  页面头部导航栏副标题配置
    [params.header.subtitle]
      # 副标题名称
      name = "Yangliuly1's blog"
      # 是否为副标题显示打字机动画
      typeit = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # FixIt NEW | 0.2.0 自定义内容（支持 HTML 格式）
    # custom = ""
    # FixIt NEW | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # FixIt NEW | 0.2.0 是否显示版权信息
    copyright = true
    #  是否显示作者
    author = true
    # 网站创立年份
    since = 2022
    #  网站创立时间
    siteTime = "2022-01-01T16:15:22+08:00" # 例："2022-01-01T16:15:22+08:00"
    #  公网安备信息，仅在中国使用（支持 HTML 格式）
    gov = ""
    #  ICP 备案信息，仅在中国使用（支持 HTML 格式）
    icp = ""
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  #  Section（所有文章）页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 20
    # FixIt NEW | 0.2.13 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10

  # FixIt NEW | 0.2.0 List（目录或标签）页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 20

  # FixIt 0.2.17 | 标签云配置
  [params.tagcloud]
    enable = true
    min = 14 # 最小字体大小，单位：px
    max = 32 # 最大字体大小，单位：px
    peakCount = 10 # 每个标签的最大文章数
    orderby = "name" # 标签排序方式，可选值：["name", "count"]

  # 主页配置
  [params.home]
    # FixIt NEW | 0.2.0 RSS 文章数目
    rss = 20
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "imgs/favicon/safari-pinned-tab.svg"
      # FixIt 0.2.17 | NEW 头像菜单链接的 identifier
      avatarMenu = "about"
      # FixIt CHANGED | 0.2.7 主页显示的网站标题（支持 HTML 格式）
      title = "个人博客"
      # 主页显示的网站副标题
      subtitle = "相信自己，改变自己！"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      #  免责声明（支持 HTML 格式）
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 10

  #  作者的社交信息设置
  [params.social]
    GitHub = "Yangliuly1"
    Weibo = ""
    Email = "yangliuly1993@gmail.com"
    RSS = true
    Stackoverflow = ""
    Zhihu = ""
    Douban = ""
    Gitea = ""
    Bilibili = ""
    BuyMeaCoffee = ""
    Linktree = ""
    QQ = ""
    QQGroup = ""
    CSDN = ""

  # FixIt CHANGED | 0.2.0 文章页面配置
  [params.page]
    # FixIt NEW | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FixIt NEW | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FixIt NEW | 0.2.0 是否使用 twemoji
    twemoji = true
    # 是否使用 lightgallery
    lightgallery = true
    # FixIt NEW | 0.2.0  是否使用 ruby 扩展语法
    ruby = true
    # FixIt NEW | 0.2.0  是否使用 fraction 扩展语法
    fraction = true
    # FixIt NEW | 0.2.0  是否使用 fontawesome 扩展语法
    fontawesome = true
    # FixIt NEW | 0.2.0 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # FixIt NEW | 0.2.0 是否在 RSS 中显示全文内容
    rssFullText = true
    # FixIt NEW | 0.2.0 页面样式 ["narrow", "normal", "wide", ...]
    pageStyle = "normal"
    # FixIt NEW | 0.2.0 强制使用 Gravatar 作为作者头像
    gravatarForce = false
    # FixIt NEW | 0.2.0 开启自动书签支持
    # 如果为 true，则在关闭页面时保存阅读进度
    autoBookmark = true
    # FixIt NEW | 0.2.0 是否使用 字数统计
    wordCount = true
    # FixIt NEW | 0.2.0 是否使用 预计阅读
    readingTime = true
    # FixIt NEW | 0.2.0 文章结束标志
    endFlag = "（完）"


    # FixIt NEW | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      #  是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
      #  目录位置 ["left", "right"]
      position = "right"
    # FixIt NEW | 0.2.13  在文章开头显示提示信息，提醒读者文章内容可能过时
    [params.page.expirationReminder]
      enable = false
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = true
    # FixIt 0.2.16 | CHANGED KaTeX 数学公式 (https://katex.org)
    [params.page.math]
      enable = true
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # FixIt NEW | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      #  是否显示代码块的编辑按钮
      edit = true
      # 默认展开显示的代码行数
      maxShownLines = 50
    # FixIt NEW | 0.2.1 文章编辑
    [params.page.edit]
      enable = false
      # FixIt 0.2.15 | CHANGED 编辑的基础链接
      # url = "/edit/branch-name/subdirectory-name" # 相对于 `params.gitRepo`
      # url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # 完整链接
      url = "/edit/docs/content"
    #  FixIt NEW | 0.2.0  Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    #  FixIt 0.2.17 | NEW 赞赏设置
    [params.page.reward]
      enable = true
      animation = true
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "before"
      comment = "Buy me a coffee~"
      [params.page.reward.ways]
        # wechatpay = "imgs/favicon/safari-pinned-tab.svg" #TODO
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
    # FixIt CHANGED | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Weibo = true
      Baidu = true
    # FixIt CHANGED | 0.2.14 评论系统设置 #TODO
    [params.page.comment]
      enable = true
      # Valine 评论系统设置 (https://github.com/xCss/Valine)
      [params.page.comment.valine]  
        enable = true
        appId = "MTXT4R9Iekm2uFGia5Lb6uiH-gzGzoHsz"
        appKey = "KY7EN9JqXaGdQFFGSc65GYiD"
        placeholder = "ヾﾉ≧∀≦)o~ 有事请留言！\n评论功能以邮件作为通知方式！\n如有必要请填写正确邮箱哦！"
        avatar = "wavatar"
        meta= ""
        pageSize = 10
        lang = "zh-CN"
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = true
        serverURLs = ""
        #  emoji 数据文件名称，默认是 "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # 位于 "themes/FixIt/assets/lib/valine/emoji/" 目录
        # 可以在你的项目下相同路径存放你自己的数据文件：
        # "assets/lib/valine/emoji/"
        emoji = ""
        commentCount = true # FixIt NEW | 0.2.13
    # FixIt NEW | 0.2.7 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    #  页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = "Yangliuly1"
        logoUrl = "/imgs/favicon/safari-pinned-tab.svg"

  # FixIt NEW | 0.2.5 TypeIt 配置
  [params.typeit]
    # 每一步的打字速度（单位是毫秒）
    speed = 100
    # 光标的闪烁速度（单位是毫秒）
    cursorSpeed = 1000
    # 光标的字符（支持 HTML 格式）
    cursorChar = "|"
    # 打字结束之后光标的持续时间（单位是毫秒，"-1" 代表无限大）
    duration = -1

  # FixIt 0.2.15 | NEW Mermaid 配置
  [params.mermaid]
    # 取值详见 https://mermaid-js.github.io/mermaid/#/Setup?id=theme
    themes = ["forest", "dark"]
  
  # FixIt NEW | 0.2.12 盘古之白配置
  [params.pangu]
    # 适用于中文写作用户
    enable = true
  
  # FixIt NEW | 0.2.12 水印配置
  # 详细参数见 https://github.com/Lruihao/watermark#readme
  [params.watermark]
    enable = true
    # 水印内容（允许 HTML 格式）
    content = '<img style="height: 0.85rem;" src="/imgs/favicon/safari-pinned-tab.svg" alt="logo" /> Yangliuly1'
    # 水印透明度
    opacity = 0.0125
    # 水印父节点
    appendTo = ".wrapper>main"
    # 单水印宽度 单位：px
    width = 150
    # 单水印高度 单位：px
    height = 20
    # 水印行间距 单位：px
    rowSpacing = 60
    # 水印列间距 单位：px
    colSpacing = 30
    # 水印旋转角度 单位：deg
    rotate = 15
    # 水印字体大小，单位：rem
    fontSize = 1.1
    #  水印字体
    fontFamily = "MMT_LRH,沐目体"

  # FixIt NEW | 0.2.12 不蒜子统计
  [params.ibruce]
    enable = true
    # 在文章中开启
    enablePost = true

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""

  # FixIt NEW | 0.2.10 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = "/imgs/favicon/safari-pinned-tab.svg"
    # 缩略图 URL
    thumbnailUrl = "/imgs/favicon/safari-pinned-tab.svg"

  # FixIt NEW | 0.2.10 网站分析配置
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

  # FixIt NEW | 0.2.7 Cookie 许可配置
  [params.cookieconsent]
    enable = true
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # FixIt CHANGED | 0.2.7 CDN 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称，默认不启用 ["jsdelivr.yml", "unpkg.yml", ...]
    # 位于 "themes/FixIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件："assets/data/cdn/"
    # data = "unpkg.yml"

  # FixIt NEW | 0.2.8 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

  # FixIt NEW | 0.2.14 在左上角或者右上角显示 GitHub 开源链接
  [params.githubCorner]
    enable = true
    permalink = "https://github.com/Yangliuly1"
    title = "个人 GitHub，请点 Star!"
    position = "right" # ["left", "right"]

  #  FixIt NEW | 0.2.14 Gravatar 设置
  [params.gravatar]
    # Gravatar 主机，默认：“www.gravatar.com”
    host = "gravatar.loli.ne" # ["cn.gravatar.com", "gravatar.loli.net", ...]
    style = "mp" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]

  # FixIt 0.2.16 | NEW 返回顶部
  [params.backToTop]
    enable = true
    # 在 b2t 按钮中显示滚动百分比
    scrollpercent = true

  # FixIt 0.2.16 | NEW 阅读进度条
  [params.readingProgress]
    enable = true
    # 可用值：["left", "right"]
    start = "left"
    # 可用值：["top", "bottom"]
    position = "top"
    reversed = false
    light = "var(--fi-success)"
    dark = "var(--fi-success-dark)"
    height = "2px"

  # FixIt 0.2.17 | NEW  定义自定义文件路径
  # 在站点目录 `layouts/partials/custom` 中创建您的自定义文件，并取消注释下面需要的文件
  [params.customFilePath]
    # aside = "custom/aside.html"
    profile = "custom/profile.html"
    # footer = "custom/footer.html"

  # FixIt 0.2.15 | NEW 开发者选项
  [params.dev]
    enable = false
    # 检查更新
    c4u = false
    # 请勿公开展示！
    githubToken = ""
    # 移动端开发者工具配置
    [params.dev.mDevtools]
      enable = false
      # 支持 "vConsole", "eruda"
      type = "vConsole"

# -------------------------------------------------------------------------------------
# Hugo Settings for theme FixIt
# -------------------------------------------------------------------------------------

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ################## 必要的配置 ##################
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false 
    ################## 必要的配置 ##################
    guessSyntax = true
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "Yangliuly1"
  email = "yangliuly@gmail.com"
  link = "https://github.com/Yangliuly1"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"
  private = ":sections[1:]/:filename"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/) 
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# FixIt CHANGED | 0.2.15
[mediaTypes]
  # 用于输出 Markdown 格式文档的设置
  [mediaTypes."text/markdown"]
    suffixes = ["md"]
  # 用于输出 txt 格式文档的设置
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

# FixIt CHANGED | 0.2.15
[outputFormats]
  # 用于输出 Markdown 格式文档的设置
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  #  用于输出 baidu_urls.txt 文件的设置
  [outputFormats.BaiduUrls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# FixIt CHANGED | 0.2.1 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON", "BaiduUrls"]  # JSON: index.json用于algolia搜索
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]


